name: "S3limitList"

on:
  push:
    branches:
      - "master"



jobs:
  test_github_oidc:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: "test_github_oidc"
        uses:  aws-actions/configure-aws-credentials@master
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::771794531895:role/S3BucketList-role
          role-session-name: MySessionName
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - run: aws s3 ls