name: "S3limitList"

on:
  push:
    branches:
      - "master"



jobs:
  test_github_oidc:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: "test_github_oidc"
        uses:  aws-actions/configure-aws-credentials@master
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::771794531895:role/S3BucketList-role
          role-session-name: MySessionName
      - run: 
          aws s3 ls