name: "S3limitList"

on:
  schedule:
    - cron: "10 6 * * *" # 定期実行のコマンド
    # Allows you to run this workflow manually from the Actions tab 
  workflow_dispatch:

jobs:
  s3limitchecker:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
           aws-region: ap-northeast-1
           role-to-assume: ${{ env.AWS_ROLE_ARN }}
           role-session-name: S3BucketList-role
      #  - name: Configure AWS credentials
      #    uses: aws-actions/configure-aws-credentials@v1
      #    with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ap-northeast-1
       - name: "main shell"
         run: |
          pip3 install boto3
          pip3 install virtualenv --user
          virtualenv limitchecker
          source limitchecker/bin/activate
          pip install awslimitchecker
          echo "1----------------------------------"
          python --version
          
          LIMIT_JP=`awslimitchecker -l | grep "S3" | awk '{print $2}'`
          NOW_JP=`awslimitchecker -u | grep "S3" | awk '{print $2}'`

          PERSENT=100
          echo "----------------------------------"
          ((AAA_JP= NOW_JP * PERSENT))
          ((RATE_JP= AAA_JP / LIMIT_JP))

          if [ "$RATE_JP" -gt 60 ]
          then
          MESSAGE="現在のテストアカウントのS3バケットの使用率は、\n 最大 $LIMIT_JP 中 $NOW_JP 個使用中。割合$RATE_JP %"

          #Incoming WebHooks送信
          DATA="{'channel': '#shiihara makoto', 'username': '警告', 'text': '$MESSAGE', 'icon_emoji': ':cop:'}"

          curl -X POST https://hooks.slack.com/services/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 -d "$DATA"

          fi