# 名前は適当に
name: test

on:
master branch
  #ルールも適当に
  push:
    branches: [ master ]
permissions:
  id-token: write
  contents: write
jobs:
  build:
    steps:
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::771794531895:role/S3BucketList-role
          role-session-name: MySessionName
      - run: aws sts get-caller-identity
       # 以下はS3にあげる処理。基本的に認証が通れば、aws cliで操作できるようになる
      - name: Deploy to S3
        run: aws sts get-caller-identity