name: "ci"

on: [ workflow_dispatch ]

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # 指定が必要

    steps:
      - uses: actions/checkout@v2

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.arn:aws:iam::771794531895:role/S3BucketList-role }} # 作成したIAMロールのARN
          role-session-name: S3limitList # CloudTrailイベントに表示されるユーザー名
          aws-region: ap-northeast-1

      - run: aws sts get-caller-identity

      - run: aws s3 ls